### ISSUE TITLE
SaliencyMap

### ISSUE THREAD

**Issue by GuLicheng** [maeve07/RCA#10]
I see some path in your code(gen_labels.py):
"""
im_path = data_path + 'JPEGImages/'
sal_path = data_path + 'saliency_map'
"""
Have you ever use a thirdpart saliency map in your model?

**Comment by guangpintao** [comment]
<img width="636" alt="image" src="https://user-images.githubusercontent.com/32570671/187846904-e74fd089-e4fb-4e7f-ab3c-e0af9c8de0b4.png">

It can be found here: https://drive.google.com/file/d/1ENS6jR6EUIDtxWsYwgwZ9YELSp0tFQ0k/view?usp=sharing

**Comment by tfzhou** [comment]
Thanks @Gptao. @GuLicheng, in our experiments, we indeed need saliency maps to generate better pseudo masks, which is widely adopted in existing WSSS models.

**Comment by shifan-Z** [comment]
Thanks for posting your excellent code! 
I wander if I want to use your work on my dataset, how can I get the saliency_map?

**Comment by guangpintao** [comment]
A simple pooling-based design for realtime salient object detection. https://github.com/backseason/PoolNet

**Comment by shifan-Z** [comment]
Thank you so much!
