### ISSUE TITLE
gen_labels报错求解

### ISSUE THREAD

**Issue by YkiWu** [maeve07/RCA#16]
作者您好！我在运行gen_labels时出现了这个报错
<img width="815" alt="1" src="https://user-images.githubusercontent.com/127412466/224039737-f6947908-67c0-4bbc-b894-eb07a26c4095.png">
我看这里sal是从VOC2012下直接读saliency_map,您给的下载链接里并没有找到这部分，请问这个怎么解决呢？

**Comment by vicent303** [comment]
> 作者您好！我在运行gen_labels时出现了这个报错 <img alt="1" width="815" src="https://user-images.githubusercontent.com/127412466/224039737-f6947908-67c0-4bbc-b894-eb07a26c4095.png"> 我看这里sal是从VOC2012下直接读saliency_map,您给的下载链接里并没有找到这部分，请问这个怎么解决呢？

It can be found here: https://drive.google.com/file/d/1ENS6jR6EUIDtxWsYwgwZ9YELSp0tFQ0k/view?usp=sharing

**Comment by YkiWu** [comment]
> 
Thank you for your timely reply! And now I encounter the same question in another issue that 'zero-size array to reduction operation maximum which has no identity' and I am waiting for your solution sincerely!

**Comment by vicent303** [comment]
我也遇到了同样的问题，也许你可以从 #15 中找到答案

**Comment by YkiWu** [comment]
> 我也遇到了同样的问题，也许你可以从 #15 中找到答案

嗯嗯是的，我已经看过#15了，所以该怎么解决这个orig为空的问题呢？我好像没有理解这个Bug的解决方案，或许您现在有解决方法了吗？

**Comment by vicent303** [comment]
> > 我也遇到了同样的问题，也许你可以从 #15 中找到答案
> 
> 嗯嗯是的，我已经看过#15了，所以该怎么解决这个orig为空的问题呢？我好像没有理解这个Bug的解决方案，或许您现在有解决方法了吗？

******抱歉，我也没有很好的解决方法，如果您解决了，还请不吝赐教**

**Comment by tfzhou** [comment]
Hi guys, I will look into the issue later today. Will back to you as soon as I can.

**Comment by vicent303** [comment]
> Hi guys, I will look into the issue later today. Will back to you as soon as I can.

Okey! Thanks for your efforts.

**Comment by YkiWu** [comment]
> Hi guys, I will look into the issue later today. Will back to you as soon as I can.

OK, thanks!

**Comment by tfzhou** [comment]
Hi guys, could you try to see `res.py`? to be honest, I did not carefully check the functionality of the script, but I guess it is the solution.

**Comment by vicent303** [comment]
Thanks! I have solved it.

**Comment by zbb1111** [comment]
Hello, how can I solve this problem? Can you tell me the specific method？
