### ISSUE TITLE
How to dram the heatmap?

### ISSUE THREAD

**Issue by xiewende** [maeve07/RCA#2]
Nice work!

can you shape with me how to draw the heatmap liked Fig.3?

![1651195698(1)](https://user-images.githubusercontent.com/46392987/165872230-3b559be7-5a9a-4090-87f7-b1fd2199598c.jpg)

**Comment by tfzhou** [comment]
Hi @xiewende, Thanks for your interests. 

Each heatmap in this figure is one column in _S_ (Eq.7), which is reshaped to (WxH).
