### ISSUE TITLE
size mismatch in `gen_labels` procedure

### ISSUE THREAD

**Issue by xh-zh** [maeve07/RCA#5]
Hi, thanks for disclosing such excellent work!

I am repeating your experiment. What confusing me is the size mismatch in `gen_labels` procedure. 
The function [`crf_inference`](https://github.com/maeve07/RCA/blob/main/utils/imutils.py#L218) requires `img` and `probs` of the same size. But I fond the size of attention map generated [here](https://github.com/maeve07/RCA/blob/main/models/rca.py#L164) is smaller than that of the origin image. Have you resized the attention map to the origin size befor `gen_labels` procedure?

**Comment by tfzhou** [comment]
Hi @xh-zh, please try to upsample the attention map.
