### ISSUE TITLE
About val_cls.txt

### ISSUE THREAD

**Issue by 911456451** [maeve07/RCA#7]
Your work is brillient and impressive, and I want to train the model, but there is no val_cls.txt, could you please tell where to find val_cls.txt file, thank you so much!

**Comment by maeve07** [comment]
Hello, thanks for the interests. It can be downloaded from https://drive.google.com/file/d/1rYrgSxoo2jcJdEPDcFqfVpwK5_QmDPDC/view?usp=sharing

**Comment by halbielee** [comment]
Hello, @maeve07 
Thanks for your kind reply, but I cannot download the 'val_cls.txt' file from the link because of the access permission.
Can you share the linke without the permission?
Thanks!

**Comment by 911456451** [comment]
Very thanks for your reply !




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "maeve07/RCA"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月6日(星期三) 中午11:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [maeve07/RCA] About val_cls.txt (Issue #7)





 
Hello, thanks for the interests. It can be downloaded from https://drive.google.com/file/d/1rYrgSxoo2jcJdEPDcFqfVpwK5_QmDPDC/view?usp=sharing
